<?php
class Home extends CI_Controller
{
	public function __construct()
	{
		parent::__construct();
		$this->load->model("user_model");
		if($this->session->has_userdata("uid"))
		{
			$uid=$this->session->userdata("uid");
			$count=$this->user_model->cart_count($uid);
		}
		else
		{
			$uid=0;
			$count=$this->user_model->cart_count($uid);
		}
		$cart=$this->user_model->get_cart($uid);
		$amount=0;
		foreach($cart as $cart)
		{
			$amount+=$cart->price;
		}
		$GLOBALS['amount']=$amount;
	}
	public function index()
	{	
		if($this->input->post("add_cart"))
		{
			$data["title"]=$this->input->post("title");
			$data["price"]=$this->input->post("price");
			$data["product_image1"]=$this->input->post("product_image1");
			$data["product_id"]=$this->input->post("product_id");
			$data["user_id"]=$this->input->post("user_id");
			$pid=$data["product_id"];
			if($this->session->has_userdata("uid"))
			{
				$uid=$this->session->userdata("uid");
			}
			else
			{
				$uid=0;
			}
			if($this->user_model->check_exist_cart($pid,$uid))
			{
				echo "<script>alert('already this product added to cart');</script>";
			}
			else
			{
				$response=$this->user_model->add_cart($data);
				if($response==true)
				{
					echo "<script>alert('Add to cart successfully');</script>";
				}
				else
				{
					echo "<script>alert('Error to add cart');</script>";
				}
		    }
		}
		$category=$this->user_model->get_category();
		$brand=$this->user_model->get_brand();
		if($this->input->get("id"))
		{
			if($this->session->has_userdata("uid"))
		{
			$uid=$this->session->userdata("uid");
			$count=$this->user_model->cart_count($uid);
		}
		else
		{
			$uid=0;
			$count=$this->user_model->cart_count($uid);
		}
			$id=$this->input->get("id");
			$products=$this->user_model->get_product($id);
			
			$this->load->view("header",array("count"=>$count,"amount"=>$GLOBALS['amount']));
			$this->load->view("home",array("category"=>$category,"brand"=>$brand,"products"=>$products,"count"=>$count));
		}
		elseif($this->input->get("search"))
		{
			if($this->session->has_userdata("uid"))
		{
			$uid=$this->session->userdata("uid");
			$count=$this->user_model->cart_count($uid);
		}
		else
		{
			$uid=0;
			$count=$this->user_model->cart_count($uid);
		}
			$search=$this->input->get("search");
			$products=$this->user_model->get_search_product($search);
			$this->load->view("header",array("count"=>$count,"amount"=>$GLOBALS['amount']));
			$this->load->view("home",array("category"=>$category,"brand"=>$brand,"products"=>$products,"count"=>$count));
		}
		elseif($this->input->get("category_id"))
		{
			if($this->session->has_userdata("uid"))
		{
			$uid=$this->session->userdata("uid");
			$count=$this->user_model->cart_count($uid);
		}
		else
		{
			$uid=0;
			$count=$this->user_model->cart_count($uid);
		}
			$category_id=$this->input->get("category_id");
			$products=$this->user_model->get_category_product($category_id);
			$this->load->view("header",array("count"=>$count,"amount"=>$GLOBALS['amount']));
			$this->load->view("home",array("category"=>$category,"brand"=>$brand,"products"=>$products,"count"=>$count));
		}
		elseif($this->input->get("brand_id"))
		{
			if($this->session->has_userdata("uid"))
		{
			$uid=$this->session->userdata("uid");
			$count=$this->user_model->cart_count($uid);
		}
		else
		{
			$uid=0;
			$count=$this->user_model->cart_count($uid);
		}
			$brand_id=$this->input->get("brand_id");
			$products=$this->user_model->get_brand_product($brand_id);
			$this->load->view("header",array("count"=>$count,"amount"=>$GLOBALS['amount']));
			$this->load->view("home",array("category"=>$category,"brand"=>$brand,"products"=>$products,"count"=>$count));
		}
		else
		{
			if($this->session->has_userdata("uid"))
		{
			$uid=$this->session->userdata("uid");
			$count=$this->user_model->cart_count($uid);
		}
		else
		{
			$uid=0;
			$count=$this->user_model->cart_count($uid);
		}
		$products=$this->user_model->get_products();
		$this->load->view("header",array("count"=>$count,"amount"=>$GLOBALS['amount']));
		$this->load->view("home",array("category"=>$category,"brand"=>$brand,"products"=>$products,"count"=>$count));
		}
	}
	public function cart()
	{
		if($this->session->has_userdata("uid"))
		{
			$uid=$this->session->userdata("uid");
			$count=$this->user_model->cart_count($uid);
		}
		else
		{
			$uid=0;
			$count=$this->user_model->cart_count($uid);
		}
		$cart=$this->user_model->get_cart($uid);
		if($this->input->post("update_cart"))
		{
			$cart_id=$this->input->post("cart_id");
			$price=$this->input->post("price");
			$quantity=$this->input->post("quantity");
			$price=(int)$price*(int)$quantity;
			$response=$this->user_model->update_cart($cart_id,$price);
			if($response==true)
			{
				echo "<script>alert('cart updated successfully');window.location.replace(window.location.href);</script>";
			}
			else
			{
				echo "<script>alert('Error to update a cart');window.location.replace(window.location.href);</script>";
			}
		}
		if($this->input->post("delete_cart"))
		{
			$cart_id=$this->input->post("cart_id");
			$response=$this->user_model->delete_cart($cart_id);
			if($response==true)
			{
				echo "<script>alert('Product removes from cart  successfully');window.location.replace(window.location.href);</script>";
			}
			else
			{
				echo "<script>alert('Error to remove a product from cart');window.location.replace(window.location.href);</script>";
			}
		}
		$this->load->view("header",array("count"=>$count,"cart"=>$cart,"amount"=>$GLOBALS['amount']));
		$this->load->view("cart");
		$this->load->view("footer");
	}
	public function checkout()
	{
		if($this->session->has_userdata("uid"))
		{
			$uid=$this->session->userdata("uid");
			$count=$this->user_model->cart_count($uid);
		}
		else
		{
			$uid=0;
			$count=$this->user_model->cart_count($uid);
		}
		if($count>0)
		{
		  $this->load->view("header",array("count"=>$count,"amount"=>$GLOBALS['amount']));
		  $this->load->view("checkout");
		}
		else
		{
			echo "<script>alert('Please add atleast one product to continue');</script>";
			redirect("home/cart");
		}
	}
	public function orders()
	{
		if($this->session->has_userdata("uid"))
		{
			$uid=$this->session->userdata("uid");
			$count=$this->user_model->cart_count($uid);
		}
		else
		{
			$uid=0;
			$count=$this->user_model->cart_count($uid);
		}
		$invoice_number=123041+$this->user_model->order_count();
		$cart=$this->user_model->get_cart($uid);
		$total=0;
		foreach($cart as $cart)
		{
			$total+=$cart->price;
		}
		$data["user_id"]=$uid;
		$data["total_products"]=$count;
		$data["invoice_no"]=$invoice_number;
		$data["amount_due"]=$total;
		$last_id=$this->user_model->add_orders($data);
		$cart=$this->user_model->get_cart($uid);
		foreach($cart as $cart)
		{
			$data2["title"]=$cart->title;
			$data2["price"]=$cart->price;
			$data2["product_image1"]=$cart->product_image1;
			$data2["product_id"]=$cart->product_id;
			$data2["user_id"]=$cart->user_id;
			$data2["order_id"]=$last_id;
			$this->user_model->add_final($data2);
		}
		$response=$this->user_model->delete_old_cart($uid);
		if($response==true)
		{
			$success="<script>alert('Order submitted successfully');</script>";
			$this->session->set_flashdata("success",$success);
			redirect("user/pending_orders");
		}
		else
		{
			
			$success="<script>alert('Error to place a order');</script>";
			$this->session->set_flashdata("success",$success);
			redirect("user/pending_orders");
		}

	}
	public function products()
	{
		
		if($this->input->post("add_cart"))
		{
			$data["title"]=$this->input->post("title");
			$data["price"]=$this->input->post("price");
			$data["product_image1"]=$this->input->post("product_image1");
			$data["product_id"]=$this->input->post("product_id");
			$data["user_id"]=$this->input->post("user_id");
			$pid=$data["product_id"];
			if($this->session->has_userdata("uid"))
			{
				$uid=$this->session->userdata("uid");
			}
			else
			{
				$uid=0;
			}
			if($this->user_model->check_exist_cart($pid,$uid))
			{
				echo "<script>alert('already this product added to cart');</script>";
			}
			else
			{
				$response=$this->user_model->add_cart($data);
				if($response==true)
				{
					echo "<script>alert('Add to cart successfully');</script>";
				}
				else
				{
					echo "<script>alert('Error to add cart');</script>";
				}
		    }
		}
		$category=$this->user_model->get_category();
		$brand=$this->user_model->get_brand();
		if($this->input->get("id"))
		{
			if($this->session->has_userdata("uid"))
		{
			$uid=$this->session->userdata("uid");
			$count=$this->user_model->cart_count($uid);
		}
		else
		{
			$uid=0;
			$count=$this->user_model->cart_count($uid);
		}
			$id=$this->input->get("id");
			$products=$this->user_model->get_product($id);
			$this->load->view("header",array("count"=>$count,"amount"=>$GLOBALS['amount']));
			$this->load->view("products",array("category"=>$category,"brand"=>$brand,"products"=>$products,"count"=>$count));
		}
		elseif($this->input->get("search"))
		{
			if($this->session->has_userdata("uid"))
		{
			$uid=$this->session->userdata("uid");
			$count=$this->user_model->cart_count($uid);
		}
		else
		{
			$uid=0;
			$count=$this->user_model->cart_count($uid);
		}
			$search=$this->input->get("search");
			$products=$this->user_model->get_search_product($search);
			$this->load->view("header",array("count"=>$count,"amount"=>$GLOBALS['amount']));
			$this->load->view("products",array("category"=>$category,"brand"=>$brand,"products"=>$products,"count"=>$count));
		}
		elseif($this->input->get("category_id"))
		{
			if($this->session->has_userdata("uid"))
		{
			$uid=$this->session->userdata("uid");
			$count=$this->user_model->cart_count($uid);
		}
		else
		{
			$uid=0;
			$count=$this->user_model->cart_count($uid);
		}
			$category_id=$this->input->get("category_id");
			$products=$this->user_model->get_category_product($category_id);
			$this->load->view("header",array("count"=>$count,"amount"=>$GLOBALS['amount']));
			$this->load->view("products",array("category"=>$category,"brand"=>$brand,"products"=>$products,"count"=>$count));
		}
		elseif($this->input->get("brand_id"))
		{
			if($this->session->has_userdata("uid"))
		{
			$uid=$this->session->userdata("uid");
			$count=$this->user_model->cart_count($uid);
		}
		else
		{
			$uid=0;
			$count=$this->user_model->cart_count($uid);
		}
			$brand_id=$this->input->get("brand_id");
			$products=$this->user_model->get_brand_product($brand_id);
			$this->load->view("header",array("count"=>$count,"amount"=>$GLOBALS['amount']));
			$this->load->view("products",array("category"=>$category,"brand"=>$brand,"products"=>$products,"count"=>$count));
		}
		else
		{
			if($this->session->has_userdata("uid"))
		{
			$uid=$this->session->userdata("uid");
			$count=$this->user_model->cart_count($uid);
		}
		else
		{
			$uid=0;
			$count=$this->user_model->cart_count($uid);
		}
		$products=$this->user_model->get_products();
		$this->load->view("header",array("count"=>$count,"amount"=>$GLOBALS['amount']));
		$this->load->view("products",array("category"=>$category,"brand"=>$brand,"products"=>$products,"count"=>$count));
		}
	}
	public function contact()
	{
		if($this->session->has_userdata("uid"))
		{
			$uid=$this->session->userdata("uid");
			$count=$this->user_model->cart_count($uid);
		}
		else
		{
			$uid=0;
			$count=$this->user_model->cart_count($uid);
		}
		
		$this->load->view("header",array("count"=>$count,"amount"=>$GLOBALS['amount']));
		$this->load->view("contact");
		if($this->input->post("submit"))
		{
			$data["name"]=$this->input->post("name");
			$data["email"]=$this->input->post("email");
			$data["message"]=$this->input->post("message");
			$response=$this->user_model->contact($data);
			if($response==true)
			{
				echo "<script>alert('Contact Form submitted successfully');</script>";
			}
			else
			{
				echo "<script>alert('Error to submit contact form');</script>";
			}
		}
	}
}
?>
